### ISSUE TITLE
Switch to execa changes environment

### ISSUE THREAD

**Issue by grmartin** [sindresorhus/bin-version#10]
We updated bin-version-check to latest (from 2.1.0), which includes an update from this library. Seems at some point there was a switch from `exec` to the `execa` library. (6724e8adf5e6ee93752bab146f2436919b51f7f3)

The library execa does not seem to pass the environment from the executing script forward to the new instance unlike `exec` did. Presently this is an issue for us. I would be happy to set it myself but between the handoff from `bin-version-check` -> `bin-version` -> `execa` there seems to be to way to pass in the `opt`s object.

By the look of it, all wed need to have this functionality is to have ln 8 changed: from `return execa(bin, opts.args || ['--version'])` to `return execa(bin, opts.args || ['--version'], opts)`...

**Comment by sindresorhus** [comment]
The current version is using a very old version of `execa`. I've updated it in master. Can you try it and see if it's still a problem? `$ npm i sindresorhus/bin-version` If it's still a problem, can you provide some steps to reproduce, or even better, submit a [failing test](https://github.com/avajs/ava#failing-tests).

**Comment by grmartin** [comment]
I have yet to produce a failure test--as frustrating as that is--like what i was finding 17 days ago. Ill retry an integration run in the next day or two. Fridays are typically crazy for me, then family on holidays... might not be until Monday or Tuesday.
