### ISSUE TITLE
Also try the `version` sub-command

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/bin-version#12]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/bin-version/issues/12)

Some binaries, like `$ openssl`, show the version using a sub-command `$ openssl version` instead of a flag like `$ curl --version`. If no arguments are given, it would be useful to first try `foo --version` and then `foo version`.

We should also hard-code a list of common binaries that use the `version` sub-command, so we try that first for those. For improved performance. Binaries like, `openssl`, `swiftlint`, etc.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/bin-version/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by lbell** [comment]
Possibly related: ffmpeg (and the whole ff- family) uses `-version` (one dash).

**Comment by sindresorhus** [comment]
For anyone that wants to work on this, see the initial attempt and feedback in https://github.com/sindresorhus/bin-version/pull/13.

**Comment by stroncium** [comment]
For the record, I did try it on every possible command in my system, and after waiting for an hour and closing hundreds of windows I can say I'm fairly satisfied with result: nearly half of commands did produce a version, and a lot of ones which didn't are gui-only tools which aren't supposed to have one(though I didn't check manually) and some obscure names(so internal utils, I suppose).

**Comment by sindresorhus** [comment]
Thanks doing such thorough testing 👌
