### ISSUE TITLE
extra quotes when running grunt-contrib-compass causes failure

### ISSUE THREAD

**Issue by lpaulger** [sindresorhus/bin-version#5]
https://github.com/sindresorhus/bin-version/commit/f7fa8f32a74dd7e9bad8e978541a9e3fc8289bda

when I run my ````grunt compass```` task, it fails and it seems to be from this change. 

How should I proceed in fixing this? fix a version back?

**Comment by ldavidso** [comment]
+1

**Comment by pkannanPQ** [comment]
+1

**Comment by justinryder** [comment]
+1

**Comment by cgp** [comment]
On windows for grunt-serve causes php tasks to fail: 

```
Warning: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "'php' --version"
''php'' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by deLaDude** [comment]
Still getting an error, but its slightly different now: "Warning: Failed to execute "compass.bat --version", exit code #1 Use -- force to continue"

**Comment by sindresorhus** [comment]
Ok, latest changes reverted. Fml.
