### ISSUE TITLE
CLI version?

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/bin-version#9]
like `find-version-cli` or `bin-version-check-cli` 😄

**Comment by shinnn** [comment]
> `find-version-cli`

So close.

[https://github.com/sindresorhus/bin-version#cli](https://github.com/sindresorhus/bin-version/tree/v2.0.0#cli)

> See [find-versions-cli](https://github.com/sindresorhus/find-versions-cli).

**Comment by Kikobeats** [comment]
@shinnn but what about `bin-version-cli`

**Comment by shinnn** [comment]
As described in [the README of `find-versions-cli`](https://github.com/sindresorhus/find-versions-cli#usage), you can,

```
(your app) --version | find-versions
```

**Comment by Kikobeats** [comment]
but isn't the same, the API is not align with `bin-version`

Expected something like:

```
$ bin-version curl
7.30.0
```

**Comment by shinnn** [comment]
I still cannot imagine the use case of `bin-version-cli` although `find-versions-cli` already exists. Let's wait for the response from the project owner.

**Comment by sindresorhus** [comment]
@Kikobeats What do you need it for? Knowing your use-case would help. Like why not just `curl --version`?
